version: '3'
services:
  redhat:
    build:
      context: $PWD
      dockerfile: Dockerfile-redhat
      args:
        - IMAGE=centos:7
        - UNAME=$USER
        # - UID=1000
        # - GID=1000
    image: reproman:redhat
    container_name: reproman-redhat
    volumes:
      - $PWD:/home/$USER/reproman
      - /var/run/docker.sock:/var/run/docker.sock
  debian:
    build:
      context: $PWD
      dockerfile: Dockerfile-debian
      args:
        - IMAGE=debian:jessie
        - UNAME=$USER
        # - UID=1000
        # - GID=1000
    image: reproman:debian
    container_name: reproman-debian
    volumes:
      - $PWD:/home/$USER/reproman
      - /var/run/docker.sock:/var/run/docker.sock