#!/bin/bash

# to make sure  set -x wouldn't fail
export PS4=+
set -eux

apt-get build-dep python-apt
# Install python-apt version 0.9.3.5 for Python 2 and 3
apt-get install xz-utils
curl -O http://archive.ubuntu.com/ubuntu/pool/main/p/python-apt/python-apt_0.9.3.5.tar.xz
xz -d python-apt_0.9.3.5.tar.xz
pip install http://launchpad.net/python-distutils-extra/trunk/2.28/+download/python-distutils-extra-2.28.tar.gz python-apt_0.9.3.5.tar
rm -f python-apt_0.9.3.5.tar
