#!/bin/bash

# to make sure  set -x wouldn't fail
export PS4=+
set -eux

ver=0.9.3.5

sudo apt-get build-dep python-apt
# sudo apt-get install -y --allow-downgrades  libapt-pkg-dev=0.8.16~exp12ubuntu10.27
curl -O http://security.ubuntu.com/ubuntu/pool/main/a/apt/libapt-pkg-dev_0.8.16~exp12ubuntu10.27_amd64.deb
curl -O http://security.ubuntu.com/ubuntu/pool/main/a/apt/libapt-pkg4.12_0.8.16~exp12ubuntu10.27_amd64.deb
curl -O http://security.ubuntu.com/ubuntu/pool/main/a/apt/libapt-inst1.4_0.8.16~exp12ubuntu10.27_amd64.deb
sudo dpkg --force-downgrade -i libapt-pkg-dev_0.8.16~exp12ubuntu10.27_amd64.deb libapt-pkg4.12_0.8.16~exp12ubuntu10.27_amd64.deb libapt-inst1.4_0.8.16~exp12ubuntu10.27_amd64.deb
rm -f libapt-pkg-dev_0.8.16~exp12ubuntu10.27_amd64.deb libapt-pkg4.12_0.8.16~exp12ubuntu10.27_amd64.deb libapt-inst1.4_0.8.16~exp12ubuntu10.27_amd64.deb
sudo apt-get -f install
# Install python-apt version 0.9.3.5 for Python 2 and 3
sudo apt-get install xz-utils
curl -O http://archive.ubuntu.com/ubuntu/pool/main/p/python-apt/python-apt_$ver.tar.xz
xz -d python-apt_$ver.tar.xz
pip install http://launchpad.net/python-distutils-extra/trunk/2.28/+download/python-distutils-extra-2.28.tar.gz python-apt_$ver.tar
rm -f python-apt_$ver.tar
