#!/bin/bash

# to make sure  set -x wouldn't fail
export PS4=+
set -eux

pyver=`python -c 'import sys;print(sys.version[0])'`
cd /tmp
sudo apt-get build-dep python${pyver//2/}-apt
apt-get source python-apt
# install from sources of the current package for the system
pip install `find -maxdepth 1 -iname 'python-apt*' -type d | head -n 1`
