#!/bin/bash

# Most of this is taken directly from datalad-htcondor. (Thanks!)

set -eu

sed -e 's,/debian ,/debian-devel ,g' /etc/apt/sources.list.d/neurodebian.sources.list | \
    grep -v data | \
    sudo tee /etc/apt/sources.list.d/neurodebian-devel.sources.list
sudo apt-get update

sudo debconf-set-selections -v tools/ci/htcondor_dconf_selections
sudo apt-get install -y htcondor

# Prevent htcondor from bind-mounting a scratch directory over /tmp and
# interfering with our test location. This is necessary as of htcondor v8.7.10
printf "\\nMOUNT_UNDER_SCRATCH = /var/tmp\\n" | \
    sudo tee -a /etc/condor/condor_config

sudo service condor start

# Try twice to give condor some time to fire up.
condor_status || (sleep 5; condor_status)
condor_run 'uname -a'  # perform a test submission
